# Generated by Django 5.2.14 on 2026-05-23 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ai_easy', 'AI — Easy'), ('ai_medium', 'AI — Medium'), ('ai_hard', 'AI — Hard'), ('multiplayer', 'Multiplayer')], max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'In progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('x_won', 'X won'), ('o_won', 'O won'), ('draw', 'Draw')], default='', max_length=10)),
                ('board_state', models.CharField(default='.........', max_length=9)),
                ('turn', models.CharField(default='X', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.game')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=1)),
                ('position', models.PositiveSmallIntegerField()),
                ('move_number', models.PositiveSmallIntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='game_game_status_295efa_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='game_game_created_b8327b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('game', 'move_number'), ('game', 'position')},
        ),
    ]
