# Generated by Django 5.2.14 on 2026-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
    ]
